# .github/workflows/build-run-docker.yml
name: Build and Run Docker Container

on:   
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-run:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    # Step 1: Build Docker image
    - name: Build Docker Image
      run: docker build -t self-healing-app .

    # Step 3: Run the container if it doesn't exist
    - name: Run Docker Container
      run: |
        docker run -d --name healing-container -p 5000:5000 self-healing-app
        echo "New container created and started"

    # Step 2: Check if container exists and is running
    - name: Check if Container Exists
      id: check_container
      run: |
        if [ "$(docker ps -a --filter 'name=healing-container' --format '{{.Names}}')" ]; then
          echo "Container exists"
        else
          echo "Container does not exist"
          exit 1
        fi
