name: Check Docker Container Status and Start or Create Accordingly

on:
  workflow_dispatch:  # This allows manual triggering from the GitHub Actions UI
  schedule:
    - cron: '*/1 * * * *'  # Runs every 1 minute

jobs:
  check-and-start-container:
    runs-on: ubuntu-latest

    steps:
    # # Checkout the repository
    # - name: Checkout Code
    #   uses: actions/checkout@v3

    # Step 2: Check if the container exists
    - name: Check if Container Exists
      id: check_container
      run: |
        container_status=$(docker inspect -f '{{.State.Status}}' healing-container)
        if ["$container_status" != "running"]; then
          echo "Container is down, restarting..."
          docker start healing-container
        else
          echo "Container is running fine"
          exit 1
        fi

