# .github/workflows/self-healing-docker.yml
name: Self-Healing Docker Container

on:
  workflow_dispatch:  # Trigger the workflow manually for testing
  schedule:
    - cron: '0 8 * * *'  # Example: run daily at 8 AM

jobs:
  self-healing-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    # Step 1: Build Docker image
    - name: Build Docker Image
      run: docker build -t self-healing-app .

    # Step 2: Run the container (if not already running)
    - name: Run Docker Container
      id: run_container
      run: |
        if [ "$(docker ps --filter 'name=healing-container' --format '{{.Names}}')" ]; then
          echo "Container is already running"
        else
          if [ "$(docker ps -a --filter 'name=healing-container' --format '{{.Names}}')" ]; then
            docker start healing-container
            echo "Container started"
          else
            docker run -d --name healing-container -p 5000:5000 self-healing-app
            echo "New container created and started"
          fi
        fi

    # Step 3: Simulate a failure (Stop the container)
    - name: Simulate Failure by Stopping Container
      run: |
        docker stop healing-container
        echo "Container stopped (simulated failure)"

    # Step 4: Check if the container is stopped and restart it
    - name: Check Container Status and Restart if Stopped
      run: |
        if [ "$(docker ps --filter 'name=healing-container' --format '{{.Names}}')" ]; then
          echo "Container is running, no action needed"
        else
          echo "Container is stopped, restarting..."
          docker start healing-container
          echo "Container restarted"
        fi