name: Check Docker Container Status and Start or Create Accordingly

on:
  workflow_dispatch:  # This allows manual triggering from the GitHub Actions UI
  schedule:
    - cron: '*/1 * * * *'  # Runs every 1 minute

jobs:
  check-and-start-container:
    runs-on: ubuntu-latest

    steps:
    # Checkout the repository
    - name: Checkout Code
      uses: actions/checkout@v3

    # Step 2: Check if the container exists
    - name: Check if Container Exists
      id: check_container
      run: |
        if [ "$(docker ps -a --filter 'name=self-healing-app' --format '{{.Names}}')" ]; then
          echo "Container exists"
        else
          echo "Container does not exist"
          exit 1
        fi

    # Step 3: Start the container if it exists but is stopped
    - name: Start Existing Container
      if: success()  # Only runs if the container exists
      run: |
        if [ "$(docker ps --filter 'name=self-healing-app' --format '{{.Names}}')" ]; then
          echo "Container is already running"
        else
          docker start <container-name>
          echo "Container started"
        fi
